name: Daily Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'

jobs:
  commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 👈 this gives push permission

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Make a daily commit - 23f2000485@ds.study.iitm.ac.in
        run: |
          echo "Commit made at $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit $(date)"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
